version: 2.1

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@3.1.1

jobs:
  unit_tests:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements_dev.txt
      - run:
          name: Run tests
          command: pytest tests --cov=./ --cov-report=xml
      - codecov/upload

workflows:
  main:
    jobs:
      - unit_tests
